ShoeCart/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from admin_module.views import home, userlogin

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", home, name="home"),
    path("login/", userlogin, name="login"),
    path("core/", include("admin_module.urls")),  # Include admin app URLs
    path("brand/", include("brand_module.urls")),  # Include salon app URLs
    path("user/", include("customer_module.urls")),  # Include salon app URLs
    path("staff/", include("staff_module.urls")),  # Include salon app URLs
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(template_name="password_reset.html"),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer_module/models.py
from django.db import models

from admin_module.models import User
from brand_module.models import Product as Product


# Create your models here.
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="customer")
    phone_number = models.CharField(max_length=15, unique=True)
    foot_video = models.FileField(upload_to="foot_videos/", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username


class Cart(models.Model):
    user = models.ForeignKey(Customer, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    size = models.CharField(max_length=10, null=True, blank=True)
    quantity = models.IntegerField(default=1)
    added_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.product.name} in {self.user.user.username}'s cart"


class Order(models.Model):
    STATUS_CHOICES = [
        ("Pending", "Pending"),
        ("Delivered", "Delivered"),
        ("Cancelled", "Cancelled"),
        ("Refunded", "Refunded"),
        ("Returned", "Returned"),
    ]

    TRACK_STATUS_CHOICES = [
        ("Ready to Dispatch", "Ready to Dispatch"),
        ("Shipped", "Shipped"),
        ("Reached on Nearest Hub", "Reached on Nearest Hub"),
        ("Out For Delivery", "Out For Delivery"),
        ("Delivered", "Delivered"),
        ("Ready To Pickup", "Ready To Pickup"),
        ("Pickedup", "Pickedup")
    ]
    user = models.ForeignKey(Customer, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    size = models.CharField(max_length=10, null=True, blank=True)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    delivery_address = models.TextField(null=False, blank=False)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="Pending")
    ordered_at = models.DateTimeField(auto_now_add=True)
    track_status = models.CharField(
        max_length=100, null=True, blank=True, choices=TRACK_STATUS_CHOICES, default="Ready to dispatch"
    )
    is_delivered = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if self.is_delivered:
            self.track_status = "Delivered"
            if self.status not in ["Delivered", "Cancelled", "Refunded"]:
                self.status = "Delivered"  # Update only if not already delivered/cancelled
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.id} Order by {self.user.user.username} for {self.product.name}"
    

class Feedback(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    comment = models.TextField()
    rating = models.IntegerField()
    added_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Feedback for {self.order.product.name}"


class Transaction(models.Model):
    order = models.ForeignKey(
        Order, on_delete=models.CASCADE, related_name="transaction_set"
    )
    payment_id = models.CharField(max_length=100, unique=True)  # Reference ID
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(
        max_length=10,
        choices=[("Pending", "Pending"), ("Completed", "Completed"), ("Refunded", "Refunded")],
        default="Pending",
    )
    card_number = models.IntegerField(null=False, blank=False)
    card_expiry = models.CharField(max_length=10, null=False, blank=False)
    card_cvv = models.IntegerField(null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Transaction {self.payment_id} - {self.status}"

staff_module/forms.py
import re

from django import forms
from django.core.exceptions import ValidationError

from admin_module.models import User
from customer_module.models import Order
from staff_module.models import Staff


class StaffRegistrationForm(forms.ModelForm):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())
    phone_number = forms.CharField(max_length=15)

    class Meta:
        model = User
        fields = ["email", "username", "password", "confirm_password", "phone_number"]


    def clean_phone_number(self):
        phone_number = self.cleaned_data.get("phone_number")

        # Phone number should be 10 digits (for local numbers) or follow international format
        pattern = re.compile(r"^\+?\d{10,15}$")
        if not pattern.match(phone_number):
            raise ValidationError(
                "Enter a valid phone number (10-15 digits, can start with +)."
            )

        return phone_number

    def clean_password(self):
        password = self.cleaned_data.get("password")

        if len(password) < 8:
            raise ValidationError("Password must be at least 8 characters long.")
        if not re.search(r"[A-Za-z]", password):
            raise ValidationError("Password must contain at least one letter.")
        if not re.search(r"\d", password):
            raise ValidationError("Password must contain at least one digit.")
        if not re.search(r'[!@#$%^&*(),.?":{}|<>]', password):
            raise ValidationError(
                "Password must contain at least one special character (!@#$%^&* etc.)."
            )

        return password

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError("Passwords do not match.")
        return cleaned_data


class OrderStatusUpdateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["track_status", "is_delivered"]
        widgets = {
            "track_status": forms.Select(choices=Order.TRACK_STATUS_CHOICES),
        }

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data.get("is_delivered"):
            cleaned_data["track_status"] = "Delivered"
        return cleaned_data
    
class StaffProfileForm(forms.ModelForm):
    phone_number = forms.CharField(max_length=15, required=True)

    class Meta:
        model = Staff
        fields = ["phone_number"]

templates/staff/profile.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block title %}User Profile{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="card profile-card shadow-lg p-4">
        <h2 class="sub-title">Update User Profile</h2>

        <form method="POST" class="mt-4">
            {% csrf_token %}

            <div class="mb-3">
                <label for="id_phone_number" class="form-label">Phone Number</label>
                {{ form.phone_number }}
            </div>

            <button type="submit" class="mt-4 btn primary-btn w-100">Update Profile</button>
        </form>
    </div>
</div>
{% endblock %}

templates/staff/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-5">

    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link"  href="{% url 'user_register' %}">Register User</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'staff_register' %}">Register Staff</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'brand_register' %}">Register Brand</a>
        </li>
    </ul>

    <div class="register-form">
        <h2 class="sub-title my-4">Staff Registration</h2>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn primary-btn w-100">Register</button>
        </form>

        <p class="mt-3">
            Already have an account? <a class="forgot-password" href="{% url 'login' %}">Login here</a>
        </p>
    </div>
</div>
{% endblock %}

templates/staff/staff_dashboard.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="my-4">
        <h2 class="sub-title">📋 Order List</h2>

        {% if orders %}
        <table class="table custom-table border-table">
            <thead>
                <tr>
                    <th>Order ID</th>
                    <th>Customer</th>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for order in orders %}
                <tr>
                    <td>{{ order.id }}</td>
                    <td>{{ order.user.user.username }}</td>
                    <td>{{ order.product.name }}</td>
                    <td>{{ order.quantity }}</td>
                    <td class="{% if order.is_delivered %}status-delivered{% else %}status-pending{% endif %}">
                        {{ order.track_status }}
                    </td>
                    <td>
                        <a href="{% url 'update_order_status' order.id %}" class="btn btn-primary-sm">
                            <i class="bi bi-pencil"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p style="text-align: center; color: #777;">No orders found.</p>
        {% endif %}
    </div>
    <!-- Pagination -->
    <div class="pagination">
        {% if orders.has_previous %}
        <a href="?page=1" class="page-btn">First</a>
        <a href="?page={{ orders.previous_page_number }}" class="page-btn">Previous</a>
        {% endif %}

        <span class="current-page">Page {{ orders.number }} of {{ orders.paginator.num_pages }}</span>

        {% if orders.has_next %}
        <a href="?page={{ orders.next_page_number }}" class="page-btn">Next</a>
        <a href="?page={{ orders.paginator.num_pages }}" class="page-btn">Last</a>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/staff/update_order_status.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="card center-popup p-4 w-50">
        <h2 class="sub-title my-4">Update Order Status</h2>
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_track_status">Tracking Status:</label>
                {{ form.track_status }}
            </div>
    
            <div class="form-group">
                <label for="id_is_delivered">
                    {{ form.is_delivered.label_tag }} 
                    {{ form.is_delivered }}
                </label>
            </div>
            <div class="btn-group w-100 d-flex gap-2 mt-4">
                <a href="{% url 'staff_dashboard' %}" class="btn btn-secondary">Back to Orders</a>
                <button type="submit" class="btn primary-btn">Update Status</button>
            </div>
        </form>
    
        <br>
        
    </div>
</div>
{% endblock %}